### PR TITLE
+ Add some missing translations.

### PR DESCRIPTION
**Pull request by vistamedia**
I just added some missing translations in the file importer and the card layout.

### CODE REVIEW

**Comment by dmitriitux** [comment]
@vistamedia ok, I will accept this for the 2.x branch, but the next update will be 3.x and the internal manager will be removed and replaced with integration with Quantum Manager, and the 2.x branch will be frozen with the internal manager

**Comment by dmitriitux** [comment]
@vistamedia and errors in 3.x what you fixed and which remained I will transfer manually

**Comment by vistamedia** [comment]
I quickly fixed some little issues . This custom field is really incredible. I can't wait to see the integration with quantum manager! Thanks a lot for your work! and greeting from Paris :)

**Comment by dmitriitux** [comment]
@vistamedia I now have a 3.x branch this is 2.x I made a mistake when I did it =) I am finishing it now, then I make it out of the 2.x master and freeze it and the 3.x branch becomes the master

**Comment by dmitriitux** [comment]
@vistamedia https://github.com/JPathRu/radicalmultifield/tree/2.x
you can download and watch new, I just have to finish the generation of miniatures and a couple more moments

**Comment by dmitriitux** [comment]
though I have not finished localization in English and there will be problems for now =)

**Comment by dmitriitux** [comment]
@vistamedia I honestly didn't even expect to bring this field to the west, then what foreigners use is a shock for me =)
And for what purposes do you use the field?

**Comment by vistamedia** [comment]
If you need my help for anything, just drop me an email, I'll be very happy to help for debbuging, translations, testing or whatever you need. For now I use your field in two projects in order to buid galleries. But I plan to use it more and more in the future. 


By the way I will do a full french translation for our community (I'm a board member of joomla.fr)

**Comment by dmitriitux** [comment]
@vistamedia you can edit directly on the github, I want to finish the field in my lony, I will write to you, you can edit the translation directly on the github, while there is no normal system with a debugged translation =(

**Comment by dmitriitux** [comment]
@vistamedia By the way, you can load your Jform fields, you just need them to be adapted to the subform, in the plugin settings simply write the paths to your php field classes

and a new field "custom" will appear where you directly simply write the xml fields
Снимок экрана 2021-01-09 в 19 47 14

**Comment by vistamedia** [comment]
Awesome!

**Comment by dmitriitux** [comment]
in the new version of the field 3.x will appear:
1.integration with quantum manager
2. templates for category and item of article and user can be separated
3. it will be possible to generate previews of pictures in the joomla cache and select the cutting algorithm. In Quantum, in the new update, resizing by folders will appear, that is, you can adjust resizing for each folder pointwise and select the same cutting algorithm
4.new field type: custom, which I wrote about above

**Comment by dmitriitux** [comment]
@vistamedia and the field has a helper (you can change the find value, check, add, etc.), you can view the class, I haven't documented it in any way, phpdoc should at least be written =)))
https://github.com/JPathRu/radicalmultifield/blob/master/radicalmultifieldhelper.php#L23

**Comment by vistamedia** [comment]
WOW, that impressive, I just discovered your field yesterday and there already so may exciting news 👍 
By the way I just fixed a bug with ajax call on localhost https://github.com/vistamedia/radicalmultifield/commit/9a813b3b6dd7a36f334fc6cb7eaa0c24e7901f01
I didn't know there was a new branch at the time ;)

**Comment by dmitriitux** [comment]
@vistamedia yes, I saw it, I will correct it after the release of the new one, I will correct the old branch and freeze it

**Comment by dmitriitux** [comment]
@vistamedia there are still a couple of errors in the old version, I just threw it, because all this is related to the built-in file manager. By the way, this prototype was Quantum Manager, this was its first version =)

**Comment by dmitriitux** [comment]
after creating the field, I was offered the idea to separate the manager and make it separate

**Comment by dmitriitux** [comment]
@vistamedia these plugins will already become outdated after the release of the new version, but here are some ideas for what the field can be used for:  https://hika.su/rasshireniya/raficalmultfild/katalog-plaginov

**Comment by vistamedia** [comment]
I understand better now the history od the project ;) I visited your website already and saw the examples :) I'm a big fan of quantum manager as well. I install it on every customer website.

**Comment by dmitriitux** [comment]
@vistamedia https://github.com/Quantum-Manager/quantummanager/tree/dev
you can download the dev branch of the quantum manager component to try the new setting if you are interested (folder resize), install this dev version component after installing the current stable package

**Pull request merged**
